version: "3.9"
services:
  ui:
    build: .
    command: npm run start:dev
    environment:
      EVENT_HUB_API_URL: http://localhost:8000
    ports:
      # Service port needs to match 8081 also for Webpack HMR to work
      - "8081:8081"
    volumes:
      - .:/usr/src/app
